# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "iltempe"
description: > # this means to ignore newlines until "email:"
   Scrivo le canzoni. O almeno ci provo.

email: mtempestini@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'iltempe'
author: 'iltempe'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://iltempe.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@il_tempe'

#fill in disqus shortname to use disqus
disqus: iltempe

google_analytics: UA-47474515-2

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://x.com/iltempe
    desc: Follow me on X
    share_url: https://x.com/share
    share_title:
    share_link:

  - icon:	facebook
    url:	https://www.facebook.com/iltempefacebook/
    desc: Connect with me in Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title:
    share_link:

  - icon:	instagram
    url:	https://www.instagram.com/iltempeinsta/
    desc: Follow me on Instagram
    share_url:
    share_title:
    share_link:
 
  - icon:  tiktok
    url: https://www.tiktok.com/@iltempesong
    desc: Follow me on TikTok
    share_url:
    share_title:
    share_link:

  - icon:	youtube
    url:	https://www.youtube.com/user/ziotempe/
    desc: Follow me on Youtube
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/iltempe
    desc:	Fork me on Github
    share_url:
    share_title:
    share_link:

  - icon:	spotify
    url:	https://open.spotify.com/artist/662X8f9CUE0e8IRxppJG0D?si=ddAQktVwSQibuG8VZAVmIw
    desc:	Ascoltami su Spotify
    share_url:
    share_title:
    share_link:

  - icon:  newspaper-o
    url: https://substack.com/@iltempe
    desc: Leggimi su Substack
    share_url:
    share_title:
    share_link:


